'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { AppProvider } from "@/context/appcontext";
import {SessionProvider} from "next-auth/react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "AI Docs Generator",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="relative h-full w-full bg-slate-950">
          {/* Radial gradient background */}
          <div className="absolute bottom-0 left-0 right-0 top-0 bg-[radial-gradient(circle_500px_at_50%_200px,#3e3e3e,transparent)]"></div>
          <div className="absolute inset-0 bg-black/40 pointer-events-none"></div>

          {/* Main children content */}
          <main className="relative z-10">
            <SessionProvider>
            <AppProvider>
            <Toaster position="top-right"/>
            <Navbar/>
            {children}
            <Footer/>
            </AppProvider>
            </SessionProvider>
          </main>
        </div>
      </body>
    </html>
  );
}

